local opt = vim.opt

opt.shortmess = vim.o.shortmess .. 'c'
opt.hidden = true
opt.whichwrap = 'b,s,<,>,[,],h,l'
opt.pumheight = 10
opt.fileencoding = 'utf-8'
opt.cmdheight = 2
opt.splitbelow = true
opt.splitright = true
opt.termguicolors = true
opt.conceallevel = 0
opt.showtabline = 2
opt.showmode = false
opt.backup = false
opt.writebackup = false
opt.updatetime = 300
opt.timeoutlen = 100
opt.clipboard = "unnamedplus"
opt.hlsearch = false
opt.ignorecase = true
opt.scrolloff = 7
opt.sidescrolloff = 5
opt.mouse = "a"
opt.wrap = false
opt.number = true
opt.relativenumber = true
vim.o.cursorline = true
opt.signcolumn = "yes"
opt.tabstop = 2
opt.tabstop = 2
opt.softtabstop = 2
opt.shiftwidth = 2
opt.shiftwidth = 2
opt.autoindent = true
opt.autoindent = true
opt.expandtab = true
opt.expandtab = true
-- opt.colorcolumn = "80"
opt.wrap = true
opt.linebreak = true
